def print_data(nombre, genero, pais, edad, estatura_m, estatura_cm, num_amigos):
    print()
    print("--------------------------------------------------")
    print("Nombre:  ", nombre)
    print("Género: ", genero)
    print("País: ", pais)
    print("Edad:    ", edad, "años")
    print("Estatura:", estatura_m, "metros y", estatura_cm, "centimetros")
    print("Amigos:  ", num_amigos)
    print("--------------------------------------------------")
    print()
